### ISSUE TITLE
Filedrop integration with GW cloud SDK 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#106]
- eval or prod SDK. 
- (AMI priority, but OVA needed too)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/116515131-85c41a80-a8e9-11eb-9d98-cf26f9b6f4e4.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/116515563-14d13280-a8ea-11eb-900b-58fe934cad07.png)
