### ISSUE TITLE
Add a threat analysis to gov.uk

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#116]
Add a threat analysis to gov.uk

**Comment by MaNe2020** [comment]
@GINAGC @kekesimarti do we need something more elaborative from this?
![image](https://user-images.githubusercontent.com/70108899/117450178-2dbc9200-af41-11eb-855f-55226ffcdcbb.png)

**Comment by GINAGC** [comment]
@MaNe2020 I think from details point of view is what we can get at this moment, right? I only would like to see graphs in the 2 dashboards that we have a lists (I think we need the 2 options, as a list and as a diagram)

**Comment by MaNe2020** [comment]
@GINAGC here is with diagrams 
![image](https://user-images.githubusercontent.com/70108899/117646966-ad8a6c80-b18c-11eb-9ed6-753b988813a0.png)

I will re run govUK one more time today and add here final analysis.
Once that is done will close it.
