### ISSUE TITLE
Send back performance stats of the Rebuild and performance stats of the server

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#121]
Send back performance stats of the Rebuild and performance stats of the server

**Comment by GINAGC** [comment]
@mohitsengarr from call:

- Send performance stats of what you can see in your workflow, for example, how long it takes to upload files, from the first queue until you get the response, all possible stats to be captured and added to the current metadata json file. This is only to the 2 new endpoints:
    - /api/analyse/rebuild-zip-from-base64
    - /api/analyse/rebuild-zip-from-file

**Comment by GINAGC** [comment]
duplicated with 155
