### ISSUE TITLE
Test implementation in GW desktop

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#13]

**Comment by mohitsengarr** [comment]
![image](https://user-images.githubusercontent.com/43764140/112149731-4c6eff80-8c05-11eb-8887-239c2854518a.png)
![image](https://user-images.githubusercontent.com/43764140/112149747-5133b380-8c05-11eb-9769-fb1945eea3b6.png)
![image](https://user-images.githubusercontent.com/43764140/112149777-598bee80-8c05-11eb-97a0-4d7f284b0e6a.png)
![image](https://user-images.githubusercontent.com/43764140/112149797-5ee93900-8c05-11eb-8fe3-5cc8830579f3.png)
**Tested working OK!**

**Comment by GINAGC** [comment]
Task completed
