### ISSUE TITLE
Create a new section called SDK

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#141]
For the rebuild and analyze together.

**Comment by samarthdd** [comment]
@mohitsengarr need more details on this ticket

**Comment by Lestat06** [comment]
@mohitsengarr 
![new section](https://user-images.githubusercontent.com/6232283/120513679-cf15f700-c3cc-11eb-8aa0-128dd20b8a89.png)
 new section is there and looks good, however it looks like it has the same function like the 2 endpoints above in /analyse

also the zip file that returned had the rebuilded file inside but with a different name.
[7dd6162d-726f-4c5e-b4d8-8e472db12aa6.docx](https://github.com/k8-proxy/cs-k8s-api/files/6585955/7dd6162d-726f-4c5e-b4d8-8e472db12aa6.docx)
[Clean.docx](https://github.com/k8-proxy/cs-k8s-api/files/6585959/Clean.docx)
FYI @samarthdd @GINAGC

**Comment by GINAGC** [comment]
yes, we will discuss on next demo.

**Comment by GINAGC** [comment]
@Lestat06 please open a separate issue to the rebuild file name.
