### ISSUE TITLE
Zip testing and other files support.

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#142]
**1,.- Do some testing GW Cloud API calls and confirm the following:**

- do zipped files get unpacked and sanitized individually?
- If so, does it return to its original zipped format or placed in a folder as individually cleaned files?
- if a file cannot be processed inside of the zipped file what occurs?

Please test this with the endpoint:
/api/rebuild/zipfile
and
/api/rebuild/file

Try different sets of ZIP files: only images, only PDFs, mixed formats on them. Create a table with the results and if we don't process any of them, please open a defect in this repo.

You can use this deployed server: http://3.249.175.211/ (but zip files are not supported on web, you will have to use postman)

**2.- For the file drop UI, please also validate that all the following formats can be processed. If any of those is not processed, please open a defect.**

<img width="1035" alt="Supported files GW" src="https://user-images.githubusercontent.com/70196799/117034838-f9a85d80-ad03-11eb-852d-c2a00693ffa1.png">

**Comment by GINAGC** [comment]
@Lestat06 you can use 34.240.202.210

**Comment by Lestat06** [comment]
Issue added
https://github.com/k8-proxy/cs-k8s-api/issues/154

**Comment by GINAGC** [comment]
@Lestat06 

- then no issue, that is the expected for the /rebuild/file endpoint - but these should be tested with the zip endpoint. Please confirm. 
- ok, thanks

**Comment by Lestat06** [comment]
@GINAGC 

- files were tested with both endpoints `/rebuild/file` and `/rebuild/zipfile`, raised issues for problems that i encountered in `/rebuild/zipfile`
