### ISSUE TITLE
Cloud SDK with minio version is not working offline

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/cs-k8s-api#144]
![image](https://user-images.githubusercontent.com/61416876/117310750-7b6ec700-ae7b-11eb-9626-bd8169f8c1c7.png)

**Comment by GINAGC** [comment]
OVA: s3://glasswall-sow-ova/vms/minio-gw-sdk/minio-gw-sdk-35bff4542ed76d1ad57039af2d6b9ce733759ebd-207.ova
