### ISSUE TITLE
Send the XML reports (as JSON files) to Elastic

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#150]
Add an option to send the XML reports to Elastic, so that we can have the data from XML that will lead to Thread intelligence reporting.

- send the report.json
- convert the mtadata.xml for each rebuilt file and convert it to JSON file
- send it to elasticsearch (IP that can be configured) - you can assume it will be a dedicated elasticsearch server,
- Please do these changes in the man branch, not in the minion branch.

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/118195431-d9497300-b468-11eb-8728-b282ace6044b.png)
Can see report
