### ISSUE TITLE
Two little fixes on Swagger 

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#152]
1. remove the top banner (the one saying 'Swagger' ) ,
2. put the swagger.yaml file in a better location, at the moment it is at  `swagger/v1/swagger.yaml`
![image](https://user-images.githubusercontent.com/79467690/117648711-dad81a00-b18e-11eb-98a4-ab7a8aa9caf6.png)
a good name to use is openapi.json
which is what the F2F plug is using 
![image](https://user-images.githubusercontent.com/79467690/117648789-f3483480-b18e-11eb-8c30-4e79d6f6e77c.png)

**Comment by kekesimarti** [comment]
@GINAGC I moved it.

**Comment by GINAGC** [comment]
@svf97 please test these updates, you may need to create a new AMI and test it.

**Comment by svf97** [comment]
looks like the top banner and the location are still there
![image](https://user-images.githubusercontent.com/60857664/118936100-82eaa180-b94c-11eb-94d6-b5759626195a.png)

**Comment by mohitsengarr** [comment]
@svf97 it was not merged with main before. Now it is merged. So, you can test now.

CC @GINAGC

**Comment by Lestat06** [comment]
@GINAGC this is OK.
FYI @samarthdd 

![Screenshot 2021-05-31 115401](https://user-images.githubusercontent.com/6232283/120175854-ed31fa80-c206-11eb-9a98-cd29de7dba76.png)

**Comment by samarthdd** [comment]
This is fixed

**Comment by samarthdd** [comment]
moving it to release
