### ISSUE TITLE
504 Gateway Time-out on .zip file

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#154]
Running a pdf+img.zip  in /api/rebuild/zipfile returns:
```
504 Gateway Time-out:
The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.
```
Time: 2 m 24.18 s
files used:
[pdf+img.zip](https://github.com/k8-proxy/cs-k8s-api/files/6460985/pdf%2Bimg.zip)

**Comment by mohitsengarr** [comment]
@Lestat06 is it continuously happening? and do you have any steps to reproduce?

**Comment by Lestat06** [comment]
> @Lestat06 is it continuously happening? and do you have any steps to reproduce?

@mohitsengarr this this was tried several times. I can try again but i want to try with different endpoints if that is possible

**Comment by GINAGC** [comment]
@Lestat06 yes, please try again and try to get some steps.

FYI @MaNe2020

**Comment by Lestat06** [comment]
@mohitsengarr Ok I found that the issue occurs in esxi VMs, while with APIs from AWS didn't run into this.
You can try this 91.109.25.76/api/rebuild/zipfile
with this
[pdf+img.zip](https://github.com/k8-proxy/cs-k8s-api/files/6502219/pdf%2Bimg.zip)
Will create another VM in esxi and try again with different one.
FYI @GINAGC

**Comment by GINAGC** [comment]
@mohitsengarr please take a look

**Comment by Lestat06** [comment]
@GINAGC Mohit explained what the issue is.
Quoting: "The 504 Gateway Timeout error is an HTTP status code that means that one server did not receive a timely response from another server that it was accessing while attempting to load the web page or fill another request by the browser. This usually means that the other server is down or not working properly."

Will add this in the scenarios

**Comment by GINAGC** [comment]
@Lestat06 yes, please add to the scenarios. Also, how often do we see this issue? please validate the status of the server when this happens.

**Comment by Lestat06** [comment]
@GINAGC the issue is not being repeated today. will keep an eye and test in the next days. currently the servers looks like this
![image](https://user-images.githubusercontent.com/6232283/118818683-e1644100-b8b4-11eb-9f5b-09825b44ea4e.png)

this might have been an internet issue or some pods were just running low at that moment

**Comment by Lestat06** [comment]
@GINAGC have been testing this through the week. the error hast been repeated. Do you still want me to put this to the scenarios?

**Comment by GINAGC** [comment]
@Lestat06 more than documenting, I think we need to understand when this happens and fix. Do you have more info that can help Mohit to duplicate?

**Comment by GINAGC** [comment]
Not happening anymore
