### ISSUE TITLE
We need a new endpoint called status on the REST API that returns all sorts of stats about the current server

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#155]
We need a new endpoint called status on the REST API that returns all sorts of stats about the current server:

1. CPU / Memory used
2. # of files currently being processed
3. # of files processed in last hour, last day, all the time (not 100% sure how easy it will be to map this up, but lets see it)
4. name of pod
5. Server uptime

**Comment by GINAGC** [comment]
Send performance stats of what you can see in your workflow, for example, how long it takes to upload files, from the first queue until you get the response, all possible stats to be captured and added to the current metadata json file. This is only to the 2 new endpoints:
/api/analyse/rebuild-zip-from-base64
/api/analyse/rebuild-zip-from-file

**Comment by GINAGC** [comment]
merging with https://github.com/k8-proxy/cs-k8s-api/issues/242
