### ISSUE TITLE
ErrorReport.html with .zip files

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#158]
With `/api/rebuild/zipfile`  the zip file was processed but with a `207 status`
Files were rebuild except one file which was replaced with an ErrorReport.html.
File used: 
[pdf+img.zip](https://github.com/k8-proxy/cs-k8s-api/files/6461209/pdf%2Bimg.zip)
[pdf.zip](https://github.com/k8-proxy/cs-k8s-api/files/6461231/pdf.zip)
Results:
[pdfResult.zip](https://github.com/k8-proxy/cs-k8s-api/files/6461249/pdfResult.zip)
[pdf+imgResult.zip](https://github.com/k8-proxy/cs-k8s-api/files/6461287/pdf%2BimgResult.zip)

Basically if the file with the issue is removed the process is OK and returns STATUS 200
File with issue:
[_1691664-v1-VARSS_2017_Watermark_FINALx-accessible.pdf](https://github.com/k8-proxy/cs-k8s-api/files/6461299/_1691664-v1-VARSS_2017_Watermark_FINALx-accessible.pdf)

ErrorReport.html file output:
*Archived Document Access Blocked due to Policy
The archive contained files which do not comply with the current policy
The file ids blocked are:
925aa2d1-1171-430f-b04d-6941685ceb11/68ec3e40-eea5-46c3-a27f-bf9ff035d587
For more information contact your system administrator*

**Comment by mohitsengarr** [comment]
@GINAGC it is working as expected, if zip has some files that are not processed. In this case api will return 207 with the error details returned from adaptation-service. if all files are processed without any error then api will return 200. Let me know if any changes required further.

**Comment by GINAGC** [comment]
Ok, I took a look and you are right, so it is a PDF that cannot be processed and then we add the error html. 

@Lestat06 can you start documenting this scenarios please? For example:

- what happen when all files can be processed
- what happen when not all files can be processed (this scenario)

You can add another md file here: https://github.com/k8-proxy/cs-k8s-api/tree/main/Integration

**Comment by Lestat06** [comment]
@GINAGC PR created with the scenarios https://github.com/k8-proxy/cs-k8s-api/pull/175
Added currently only to scenarios (status 200 and status 207).
will wait on feedback for this issue https://github.com/k8-proxy/cs-k8s-api/issues/154 
pls review , TIA
