### ISSUE TITLE
Test OVA/AMIs from GW Cloud SDK + file drop on CK8s

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#179]
Shereen, the purpose of this task is to give it another pass to the instructions to deploy GW Cloud SDK (API) with filedrop integrated on Compliant Kubernetes. Below all the needed information, please if you need to reach to anyone because instructions are not clear, do this on channel, so we update the documentation as needed (these pages will have customer visibility)

**OVAs:**
WC: s3://glasswall-sow-ova/vms/csapi-ck8icap/ck8-cs-api-WC-CI-wc-841981802.ova
SC: s3://glasswall-sow-ova/vms/csapi-ck8icap/ck8-cs-api-SC-CI-sc-841981802.ova

**AMIs:**
WC: eu-west-1: ami-026da32375f4b6f9a
SC: eu-west-1: ami-0904885b4dbb59bab

**Github run:** https://github.com/k8-proxy/k8s-compliant-kubernetes/runs/2583412082?check_suite_focus=true

**Instructions for AWS:** 
https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/c-fd-integration-aws

**Instructions for ESXi:** 
https://github.com/k8-proxy/cs-k8s-api/blob/main/Integration/ESXi-Deployment.md (once that you review these instructions, they need to be merged with https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/c-fd-integration)

**Instructions to get credentials:**
https://github.com/k8-proxy/cs-k8s-api/blob/main/Integration/Passwords-extraction.md

**Comment by svf97** [comment]
this was tested throughout and PR was https://github.com/k8-proxy/k8-proxy-documentation/pull/129

**Comment by svf97** [comment]
AWS testing is completely done
ESXi was being fixed by dev team as:  
1. the `wizard` didn't work on the OVAs
2. when it worked, wizard launches without login
3. we are unable to change password
4. hitting `cancel` on wizard reboots vm and relaunches `wizard`
cc: @naderaly @gurunathg
