### ISSUE TITLE
The /api/analyse/rebuild-zip-from-base64 endpoint is not working in the minio version

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#184]
![image](https://user-images.githubusercontent.com/79467690/118712109-ad3f4080-b820-11eb-953e-59a8beba49be.png)

**Comment by GINAGC** [comment]
From Mohit: 

Get: /api​/analyse​/xmlreport api will not work with minio-version. It seems you are not using the PVC "pvc-transaction-query-service" to store the reports.

**Comment by ibrahimk9000** [comment]
this issue is related to  the helms configuration , you can assign @azopat  for it

**Comment by azopat** [comment]
that PR should fix it - https://github.com/k8-proxy/go-k8s-infra/pull/78

**Comment by samarthdd** [comment]
This is fixed

**Comment by Lestat06** [comment]
@samarthdd this is working for me in minio with sdk-0.1.17

**Comment by samarthdd** [comment]
It is fixed
