### ISSUE TITLE
Unexpected API call failure with different files with issues

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#188]
Different files tested rebuilding in https://labs.glasswallsolutions.com
Doublechecked rebuild with Desktop App and https://file-drop.co.uk/
Some throw `Unexpected API call failure`
Some throw `Wrong file format`
More info found in report [here](https://docs.google.com/spreadsheets/d/194rjpjQtLtjIO7bPy1tP_-cYbkbHCCUrLmwEpFWsEUc/edit?usp=sharing)
P.S cant upload ZIP file because some files are not supported from GitHub
FYI @GINAGC

**Comment by mohitsengarr** [comment]
Estimate around 1 day @GINAGC

**Comment by ggrig** [comment]
@GINAGC 
Where can I find the files that cause the failures?

**Comment by Lestat06** [comment]
@ggrig let me check report and locate the files. Will share in cloud-sdk channel

**Comment by ggrig** [comment]
@GINAGC 
The issue does not seem to be CS SDK relevant
The files cause similar behavior with FileDrop at https://labs.glasswallsolutions.com/

**Comment by Lestat06** [comment]
@GINAGC if i recall right this was for testing filedrop  https://labs.glasswallsolutions.com itself.

**Comment by GINAGC** [comment]
@Lestat06 if this is in filedrop, then is duplicated with https://github.com/k8-proxy/k8-rebuild-file-drop/issues/44

Update issue 44 with details and close this one as duplicated please.

**Comment by Lestat06** [comment]
@GINAGC this needs further investigation also from cs-api part since the filedrop we wre testing with these files is using cs-api

**Comment by GINAGC** [comment]
@ggrig when filedrop is sending "Unexpected API call failure", which error is the cloud sdk API sending?

**Comment by GINAGC** [comment]
Sending back to @ggrig, please check previous comment.

**Comment by mohitsengarr** [comment]
@Lestat06 please provide the files that you have tested. However, it doesn't seems to be an issue with cs-api. because api will respond in a same way for all clients either file-drop, desktop or folder-to-folder.

**Comment by mohitsengarr** [comment]
@Lestat06 This is not an issue with cs-api. you can check the api separately from their UI.

Below are the swagger links for both

1. https://labs.glasswallsolutions.com/swagger/index.html
2. https://corpfiledrop.glasswallsolutions.com/swagger/index.html

if you will not get the same status from these for same file. Please open a ticket for Devops or respective team.

@GINAGC

**Comment by Lestat06** [comment]
@mohitsengarr u are right they dont htrow the same message and some files ger processed in swagger while in filedrop they throw the API error

**Comment by GINAGC** [comment]
This is duplicated with issue in the UI side: https://github.com/k8-proxy/k8-rebuild-file-drop/issues/44
