### ISSUE TITLE
Memory Leak in proxy-rest-api pod

### ISSUE THREAD

**Issue by gurunathg** [k8-proxy/cs-k8s-api#189]
Memory leak in proxy-rest-api which is making pod consume memory over a period of time

![image](https://user-images.githubusercontent.com/17300331/119355813-52479680-bcc3-11eb-9fe4-dd8e9fd3fa4f.png)
![image](https://user-images.githubusercontent.com/17300331/119355831-570c4a80-bcc3-11eb-88ec-3465fabcac2a.png)
![image](https://user-images.githubusercontent.com/17300331/119355867-612e4900-bcc3-11eb-8e80-d7e5335cfda8.png)

**Comment by GINAGC** [comment]
@gurunathg can you test this one please?

**Comment by gurunathg** [comment]
Pod health check is configured:




```
 Liveness:   http-get http://:80/api/health delay=30s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:80/api/health delay=30s timeout=1s period=30s #success=1 #failure=3
```

**Comment by gurunathg** [comment]
Primary cause - Pod is reaching out of memory due to memory leak. There was no health check configured in pod, due to which, even if pod reaches out of memory, it doesn't restart which leads to failure of service.
Healthcheck has been added to pod, so that if out of memory occurs, health check in pod fails which will restart the pod. This will free up memory and will make pod functional. As we can see, this is temporary workaround to restart pod whenever it runs out of memory

**Comment by gurunathg** [comment]
Tested in latest deployment and changes are good. No increase of memory observed

**Comment by pranaysahith** [comment]
@mohitsengarr  we are observing out of memory issues in corp filedrop which has v0.3.0 version.
can you please check why this issue is reoccurring?

**Comment by ggrig** [comment]
@pranaysahith 
Could you please share the steps to reproduce the issue?

**Comment by GINAGC** [comment]
@gurunathg can you please test this one from develop branch?

**Comment by GINAGC** [comment]
@gurunathg any update on this one?
