### ISSUE TITLE
Swagger defect: Failed to Load API definition

### ISSUE THREAD

**Issue by svf97** [k8-proxy/cs-k8s-api#200]
Issue: cache
solution: hard refresh

![image](https://user-images.githubusercontent.com/60857664/120298263-3ac36b80-c2ca-11eb-86fb-0617bc0990a3.png)

**Comment by mohitsengarr** [comment]
@GINAGC would be complete in 1 day.

**Comment by mohitsengarr** [comment]
@svf97 How often is issue is coming out? Can you please share the reproducing steps? is it still occurring?

**Comment by svf97** [comment]
@mohitsengarr this issue was for https://labs.glasswallsolutions.com:8080/swagger/index.html
no issues loading: https://cloud-sdk.glasswallsolutions.com/swagger/index.html

**Comment by GINAGC** [comment]
@mohitsengarr I still see this issue by saving and reopening the swagger page.

**Comment by mohitsengarr** [comment]
> @mohitsengarr I still see this issue by saving and reopening the swagger page.

Can you please provide the steps of action you have taken? So, I can reproduce at my side. @GINAGC

**Comment by GINAGC** [comment]
@mohitsengarr 
1.- Open swagger
2.- download as HTML page
3.- open it again in browser

**Comment by mohitsengarr** [comment]
@GINAGC we can not open the swagger from the saved html. Every time we need to access the swagger URL not the saved html.

**Comment by GINAGC** [comment]
ok, then we are closing as unable to duplicate.
