### ISSUE TITLE
Analysis API - create binary data endpoint

### ISSUE THREAD

**Issue by farringtonp** [k8-proxy/cs-k8s-api#206]
For the rebuild API, there is an endpoint to receive binary data at /api/rebuild/file

For the Analysis API, there is no corresponding endpoint and we have had requests to provide this, to avoid the user having to convert to base64 (/api/analyse/base64) prior to the call rather than sending the binary data

This issue is linked to a Sales opportunity.

**Requester: Max and Paul.**

**Comment by samarthdd** [comment]
This is done and its working

<img width="1427" alt="Screenshot 2021-06-09 at 6 11 02 PM" src="https://user-images.githubusercontent.com/64204445/121356089-2c222780-c94e-11eb-8086-b9d6e3690cd5.png">

**Comment by Lestat06** [comment]
Yes @GINAGC  we can close this. latest version 0.1.21 can access this endpoint
