### ISSUE TITLE
File should not be a zip error

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/cs-k8s-api#210]
@kekesimarti commented on [Fri May 07 2021](https://github.com/k8-proxy/go-k8s-process/issues/40)

Providing information about if a file failed to process because of a specific error or it is not processable by nature

---

@ibrahimk9000 commented on [Fri May 07 2021](https://github.com/k8-proxy/go-k8s-process/issues/40#issuecomment-834428121)

the changes will be in the go-k8s-process repo ,  maybe you can add this  issue to go-k8s-process too

---

@kekesimarti commented on [Mon May 10 2021](https://github.com/k8-proxy/go-k8s-process/issues/40#issuecomment-836880794)

@ibrahimk9000 I moved the issue to go-k8s-process repo

---

@GINAGC commented on [Fri May 28 2021](https://github.com/k8-proxy/go-k8s-process/issues/40#issuecomment-850141364)

From Mohit:

Not getting response from the queue for unsupported files

---

@ibrahimk9000 commented on [Fri May 28 2021](https://github.com/k8-proxy/go-k8s-process/issues/40#issuecomment-850299000)

this issue is fixed 

---

@Lestat06 commented on [Wed Jun 02 2021](https://github.com/k8-proxy/go-k8s-process/issues/40#issuecomment-852536139)

-@ibrahimk9000 where should we see this output in case a file fails to get processed.

-Also I tried different files with jaeger version and it looks like it cant process a lot of files:
e.g docx, powerpoint, some excel files etc, which can be processed with the classic version.
and when these files fail the output says `file should not be a zip` or `GW_FAILED` 
![image](https://user-images.githubusercontent.com/6232283/120398878-4e5aea80-c33b-11eb-8556-8a4c4f5cc30e.png)
![image](https://user-images.githubusercontent.com/6232283/120398922-5e72ca00-c33b-11eb-9d93-3e9466a0e8fa.png)

-also maybe we can add another folder where it can keep unprocessed files and their metada.json logs etc. right now if a file fails (because its unsupported) there is nothing in minio folders or in the jaeger.
And if i try to run a file with issue that i know it cant be processed i get `GW_UNPROCESSED`
![image](https://user-images.githubusercontent.com/6232283/120399255-ed7fe200-c33b-11eb-9bae-859a433e80d5.png)
FYI @GINAGC @samarthdd

**Comment by Lestat06** [comment]
@mohitsengarr this happen in the following endpoints:
```
/api/rebuild/file
/api/rebuild/zipfile
```

**Comment by samarthdd** [comment]
The issue is still there 

The error message has changed 

But when we input some docx file to api/rebuil/file API , the error is there



<img width="1429" alt="Screenshot 2021-06-15 at 8 09 09 PM" src="https://user-images.githubusercontent.com/64204445/122075114-70626b80-ce17-11eb-9132-55741457e7bd.png">

**Comment by samarthdd** [comment]
[Clean.docx](https://github.com/k8-proxy/cs-k8s-api/files/6656576/Clean.docx)

Here is the sample file

**Comment by Lestat06** [comment]
`/api/rebuild/file` still doesnt work yes
/api/rebuild/zipfile` is fixed. is currently working and processing zip files with docx

**Comment by samarthdd** [comment]
@mohitsengarr 

https://github.com/k8-proxy/data-sets/blob/main/docx/Dynamic%20Data%20Exchange.docx

https://github.com/k8-proxy/data-sets/blob/main/docx/EmbeddedImageWithIssue.docx

https://github.com/k8-proxy/data-sets/blob/main/docx/5030002_Issue_05CF00EB_05CF00DB_Sanitisation.docx

**Comment by Lestat06** [comment]
@GINAGC this is fixed we just tested.
