### ISSUE TITLE
Expose GW SDK REST API on HTTP/HTTPS instead of port 8080

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#214]

**Comment by GINAGC** [comment]
@samarthdd, @Lestat06 another to test and update documentation in all the GW Cloud SDK section please: https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/a-overview

**Comment by pranaysahith** [comment]
@samarthdd @Lestat06  The Glasswall Cloud SDK REST API should not be exposed on port 8080 now and instead it should be exposed on port 80/443.

**Comment by Lestat06** [comment]
@pranaysahith we tested this. It is working on port 80 and http.
https is still not working with the latest AMI.
FYI @GINAGC @samarthdd

**Comment by samarthdd** [comment]
@pranaysahith 

below are my observations.

I can open api in port 80 but not accessible from 443 from postman

on browser, when we hit IP, it should redirect to swagger ( like before 8080 used to redirect to 8080/swagger)

**Comment by gurunathg** [comment]
@samarthdd 
443 will be accessible only when we setup of SSL certificate to instance directly. 
Regarding redirection to swagger by default, that route is currently reserved for filedrop UI. We can add a condition to check if Filedrop is not to be installed and then add another route to redirect to swagger by default.

**Comment by Lestat06** [comment]
@gurunathg yes that would be a great feature, if filedrop is there we can access seagger with /swagger or of u have any better idea.
 And also can you show me how to setup ssl cert in instance or how to turn off ssl certification so that we can document this.

**Comment by gurunathg** [comment]
@Lestat06 In general, we need a domain name that we can assign to Instance to create SSL certificate. I am checking on possible approaches and will update

**Comment by GINAGC** [comment]
@samarthdd, @Lestat06 do you approve this to be released or anything that needs to be fixed?

**Comment by Lestat06** [comment]
yes this is validated both ports work. as far as @samarthdd obseration number 2. Gurunath and Pranay will work on a way to access Swagger by default
