### ISSUE TITLE
GW Cloud SDK performance on /api/analyse/rebuild-zip-from-base64

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#215]

**Comment by uzfarid** [comment]
@GINAGC is this new api call?

**Comment by GINAGC** [comment]
@uzfarid no, it was there before but not working. So it was redone.

**Comment by uzfarid** [comment]
I have tested this. I will generate more official report out of this. I am waiting for repo where I could store such results @GINAGC
