### ISSUE TITLE
File rebuild with different name

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#217]
The below endpoint return a zip file with metadata.json, report.xml and a cleaned file.
However the cleaned file has a different name from the original one.
/api/analyse/rebuildzip
/api/analyse/rebuild-zip-from-file
/api/SDK/rebuild-zip-from-base64
/api/SDK/rebuild-zip-from-file

files sample:
Rebuild: [7dd6162d-726f-4c5e-b4d8-8e472db12aa6.docx](https://github.com/k8-proxy/cs-k8s-api/files/6586708/7dd6162d-726f-4c5e-b4d8-8e472db12aa6.docx)
Original: [Clean.docx](https://github.com/k8-proxy/cs-k8s-api/files/6586710/Clean.docx)

**Comment by mohitsengarr** [comment]
> The below endpoint return a zip file with metadata.json, report.xml and a cleaned file.
> However the cleaned file has a different name from the original one.
> /api/analyse/rebuildzip
> /api/analyse/rebuild-zip-from-file
> /api/SDK/rebuild-zip-from-base64
> /api/SDK/rebuild-zip-from-file
> 
> files sample:
> Rebuild: [7dd6162d-726f-4c5e-b4d8-8e472db12aa6.docx](https://github.com/k8-proxy/cs-k8s-api/files/6586708/7dd6162d-726f-4c5e-b4d8-8e472db12aa6.docx)
> Original: [Clean.docx](https://github.com/k8-proxy/cs-k8s-api/files/6586710/Clean.docx)

@Lestat06 base64 endpoint would generate the random file name. However, fixed for the rebuild endpoints that are receiving file.

**Comment by GINAGC** [comment]
@Lestat06 please retest on develop-

**Comment by Lestat06** [comment]
@GINAGC this is fixed for the endpoints that receive file as Mohit mentions above. thank you Mohit
