### ISSUE TITLE
Penetration test 4.1 Test WAF - not detected on pen test

### ISSUE THREAD

**Issue by PEpetra** [k8-proxy/cs-k8s-api#303]
See penetration test report for more details

**Comment by GINAGC** [comment]
@gurunathg as agreed on meeting, share a small writeup on Pentest report comments with Infosec team.

**Comment by GINAGC** [comment]
@PEpetra we have documented this point in the secure deployment, please take a look:
https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/bcloudsdk_dep#secure-deployment-summary

**Comment by GINAGC** [comment]
@gurunathg to add CoreRuleSet  to CF template
