### ISSUE TITLE
Penetration test 4.2 HSTS header not enforced

### ISSUE THREAD

**Issue by PEpetra** [k8-proxy/cs-k8s-api#304]
Ensure that the HSTS Header is set.
 see 4.2 Of penetration test report

**Comment by mahnouman** [comment]
Hello HSTS will enforce HTTPS communication at the API code level, better to do that in the Loadbalancer level as this is where HTTPS termination would be normally implemented and response headers injections are possible,

**Comment by GINAGC** [comment]
Assigning to @gurunathg to document how this will be done in LB.

**Comment by GINAGC** [comment]
@PEpetra we have documented this point in the secure deployment, please take a look:
https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/bcloudsdk_dep#secure-deployment-summary
