### ISSUE TITLE
Penetration test 4.3 HTTP Responses

### ISSUE THREAD

**Issue by PEpetra** [k8-proxy/cs-k8s-api#305]
The application should return caching directives instructing browsers not to store local copies of any sensitive data. Often, this can be achieved by configuring the web server to prevent caching for relevant paths within the web root. Alternatively, most web development platforms allow you to control the server’s caching directives from within individual scripts. 

see 4.3 penetration test report

**Comment by GINAGC** [comment]
@Lestat06 please test this one.

**Comment by Lestat06** [comment]
@GINAGC I am not getting any output from the curl command mention in 4.3 penetration test report

**Comment by Lestat06** [comment]
@GINAGC 
this is ok. checked with endpoints too
![image](https://user-images.githubusercontent.com/6232283/123129282-20555b80-d44c-11eb-82c9-680fef6f5154.png)

**Comment by GINAGC** [comment]
@PEpetra this has been implemented and tested, will be in today's release from the Cloud SDK.
