### ISSUE TITLE
API failing when running 50 threads

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#314]
so when running it with 50 threads the api is failing with the following error .
[Web Application]:: Error Processing 'input' dccd802b-268d-453d-922f-3612f088ffb0 and error detail is None of the specified endpoints were reachable
      RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
       ---> RabbitMQ.Client.Exceptions.PossibleAuthenticationFailureException: Possibly caused by authentication failure
       ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=541, text='Unexpected Exception', classId=0, methodId=0, cause=System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
       ---> System.Net.Sockets.SocketException (104): Connection reset by peer

**Comment by Lestat06** [comment]
![image](https://user-images.githubusercontent.com/6232283/121414733-474d6100-c967-11eb-896f-47bee74d2a01.png)

**Comment by mohitsengarr** [comment]
@Lestat06 @GINAGC I have run the test using Jmeter with 50 user with 5 iteration each and I don't see even a single failure. 
![image](https://user-images.githubusercontent.com/43764140/121416087-09136a00-c986-11eb-90bb-396eb977ae52.png)

Do you have an steps how are you testing?

**Comment by kekesimarti** [comment]
FYI @mahnouman @himanshu2464

**Comment by mahnouman** [comment]
Hello @kekesimarti we have a troubleshooting session for that today.
