### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/cs-k8s-api#315]
{
"errors": [
"Error Processing 'input' f86d567c-d70e-419c-bb5b-ebc2e6d3fa02 and error detail is Object reference not set to an instance of an object."
],
"status": "GW_ERROR"
}

file like

_630675-v3-MAPI_Application_Form.docx_630675-v3-MAPI_Application_Form.docx

**Comment by samarthdd** [comment]
this is happening with minio version for SDK apis

sample file : _632499-v3-EMAs_Application_Form.docx_632499-v3-EMAs_Application_Form.docx

**Comment by mohitsengarr** [comment]
@samarthdd @GINAGC this issue is not related to `cs-k8s-api` and it will be fixed when https://github.com/k8-proxy/go-k8s-process/issues/73 is fixed. So, we can keep it open until the main issue fixed.
