### ISSUE TITLE
Redirect http to https in gw cloud sdk

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/cs-k8s-api#317]
currently APi works in both 80 and 443.

Redirect http to https

**Comment by pranaysahith** [comment]
@samarthdd @GINAGC  It makes sense to redirect a frontend app or a swagger, but if we redirect the API, it would cause trouble while accessing the API programmatically and even from postman.
we can just block the port 80 using security groups. what do you think?

**Comment by GINAGC** [comment]
@pranaysahith I agree with you. But what will happen if the user tries to access HTTP from we for example?
