### ISSUE TITLE
Review Snyc detected vulnerabilities for cs-k8s-api repo

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#320]
1. Get access to Snyc
2. For the repository assigned, do an analysis of the vulnerabilities detected.
3. Confirm if any of the vulnerabilities can quickly solved.
4. Confirm from development perspective which vulnerabilities could have high impact in product.
5. Any additional information on the analysis.

**Comment by mohitsengarr** [comment]
Fixed code vulnerabilities and created a PR https://github.com/k8-proxy/cs-k8s-api/pull/342
Remaining the deployment file one and assigned to @gurunathg
![image](https://user-images.githubusercontent.com/43764140/121847516-4ff6bc00-cd06-11eb-8e6a-7c53953a0d7a.png)

@GINAGC

**Comment by gurunathg** [comment]
Updated as part of https://github.com/k8-proxy/cs-k8s-api/pull/344. Will review further vulnerabilities

**Comment by Lestat06** [comment]
@gurunathg can u confirm that vulnerabilities in deployment part are fixed? can we close this is issue?

**Comment by GINAGC** [comment]
I validated this, this is fixed.
