### ISSUE TITLE
Fix the value of RebuildProcessingStatus

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#328]

**Comment by samarthdd** [comment]
@mohitsengarr need more info please

**Comment by samarthdd** [comment]
We have verified below messages

UNPROCESSABLE,       
INTERNAL_ERROR,        

"EXPIRED" cannot be tested until sdk expired

For CLEAN AND CLEANED, we see only 200 response

Can we get some differentiation for CLEAN or CLEANED or how can we verify these messages

**Comment by Lestat06** [comment]
Basically when we get response 200 we should get also a status update like 
`status: CLEAN`
 or 
`status: CLEANED`. 
 Like WHEN we get when GW_ERROR or GW_FAILED or UNPROCESSABLE

and to confirm CLEAN is when file is already clean
CLEANED is when file is sanitized from GW?
and in case file is CLEAN the file that we get from `response 200` DOWNLOAD is the original file correct?

**Comment by mohitsengarr** [comment]
> Basically when we get response 200 we should get also a status update like
> `status: CLEAN`
> or
> `status: CLEANED`.
> Like WHEN we get when GW_ERROR or GW_FAILED or UNPROCESSABLE
> 
> and to confirm CLEAN is when file is already clean
> CLEANED is when file is sanitized from GW?
> and in case file is CLEAN the file that we get from `response 200` DOWNLOAD is the original file correct?

@Lestat06 you can see the description of status from here https://github.com/k8-proxy/go-k8s-process#dev-section

Regarding the `clean/ cleaned` case user already get the the binary of the sanitized file with `200 `response code.
