### ISSUE TITLE
Support policies management

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#331]
- Support policies management by passing the json file to minio

**Comment by GINAGC** [comment]
@mohitsengarr please write some documentation about how to use and how to update policies. After that, I will send to QA. Thank you!

**Comment by mohitsengarr** [comment]
> @mohitsengarr please write some documentation about how to use and how to update policies. After that, I will send to QA. Thank you!

@GINAGC testing is straight, user needs to select the api to test and click on "Try it out" then the content management policy will be populated and user can make the changes in it accordingly.

**Comment by Lestat06** [comment]
@GINAGC does this issue cover this one?
https://github.com/k8-proxy/go-k8s-process/issues/49

**Comment by GINAGC** [comment]
@Lestat06 yes, this task was for the work done in the cloud sdk side, but first was the work done in minio #49. From QA perspective, you just need to review on minio version.
