### ISSUE TITLE
Unit and integration tests

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#332]
- Unit and integration tests for all endpoints

**Comment by ggrig** [comment]
The current status of the test suit is as follows - 8 test are implemented, 4 succeed, 4 fail

![image](https://user-images.githubusercontent.com/26714598/122645339-305afb80-d12b-11eb-871f-beb6061b2b01.png)

**Comment by GINAGC** [comment]
@Lestat06 for regression.

**Comment by Lestat06** [comment]
@GINAGC if this is just for regression on develop branch. currently we are blocked as we know due to know the incident here https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/71
