### ISSUE TITLE
Reduce log level from cs-api pod

### ISSUE THREAD

**Issue by gurunathg** [k8-proxy/cs-k8s-api#345]
1. Review logs sent to elastic and remove unused logs. e.g., `[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]`
2. Create configurable log level to have info, debug

**Comment by gurunathg** [comment]
Another example of log to be removed: 
`Executing ObjectResult, writing value of type '<>f__AnonymousType2`1[[System.Net.HttpStatusCode, System.Net.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]'.`

**Comment by mohitsengarr** [comment]
Estimate around 8 hours.

**Comment by ggrig** [comment]
@GINAGC 
As discussed during the meeting, I need to understand what are the complaints about logging.
Currently, we get logs in the CS SDK pods. IMHO, those are pretty restricted. 
Of course, when processing 1000s of files and getting a dozen log lines per file that may seem a lot.
In that case we need to know which particular lines for a file should be removed there

**Comment by gurunathg** [comment]
@ggrig Screenshots of logs
![Screenshot (32)](https://user-images.githubusercontent.com/17300331/125593488-1815dd17-df8f-4d5b-b58b-7462b65b5bb7.png)
![Screenshot (28)](https://user-images.githubusercontent.com/17300331/125593496-31411d49-5524-4dc5-bf8d-f70ba77d36e5.png)
![Screenshot (30)](https://user-images.githubusercontent.com/17300331/125593497-392a3566-2e13-4b4e-9444-78d65d4b2483.png)
![Screenshot (31)](https://user-images.githubusercontent.com/17300331/125593500-f6db4df2-d344-4c9d-9bfc-52db1db7eb4a.png)

**Comment by GINAGC** [comment]
@mohitsengarr sending this one to you, since Harut needs to move to F2F project.

**Comment by mohitsengarr** [comment]
Microsoft logs are configurable and `default` value is `Warning` now. if we need to update the LogLevel for Microsoft logs then it can be done by setting the environment variable `MicrosoftLogLevel`. 

Possible values for this environment variable are:

1. Trace
2. Debug
3. Information
4. Warning
5. Error 
6. Critical
7. None

**Comment by Lestat06** [comment]
It looks like the aligning and the logs are more user friendly now, @gurunathg can confirm pls

![image](https://user-images.githubusercontent.com/6232283/127521489-29128a22-be21-42f7-b1a4-f54618402b85.png)
![image](https://user-images.githubusercontent.com/6232283/127521529-b4d3606b-11f6-4d73-a382-2a012bfb95ca.png)
![image](https://user-images.githubusercontent.com/6232283/127521575-e6c5d20c-bac4-4063-8e55-8a163a827ef1.png)
