### ISSUE TITLE
Encrypted ZIP files fail in /api/rebuild/protectedzipfile endpoint

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#359]
error output
![image (2)](https://user-images.githubusercontent.com/6232283/122273249-83417280-cee1-11eb-90d3-712b8bbff50a.png)

**Comment by samarthdd** [comment]
This is resolved in 0.2.11

<img width="1423" alt="Screenshot 2021-06-17 at 6 30 04 PM" src="https://user-images.githubusercontent.com/64204445/122401322-1b9b2e00-cf9a-11eb-9fae-d1b73f28eb02.png">
