### ISSUE TITLE
Documentation improvements from release v0.2.0 and v0.3.0

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#378]
Make sure all the following is documented on the wiki:

1.- https://github.com/k8-proxy/cs-k8s-api/releases/tag/
2.- https://docs.google.com/document/d/1IKQfWKH2TRChhnD_FAKMvBs0-C2VPZm40BJzl3uuD7s/edit 

In general, the following features need to be documented:
1. - All possible status
2. - Jaeger integration 
3. - Expose GW SDK REST API on HTTP/HTTPS instead of port 8080
4. - New endpoint: Analysis API - create binary data endpoint
5. - Differentiate between a file GW does not support or cannot be processed 

This will require reviewing the doc above, testing the features and creating the documentation under GW Cloud SDK wiki.

**Comment by GINAGC** [comment]
Hi @svf97 what is the status of this one?

**Comment by svf97** [comment]
@GINAGC https://github.com/k8-proxy/k8-proxy-documentation/pull/143

**Comment by GINAGC** [comment]
https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/zother-features
and
https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/a-overview#response-status
