### ISSUE TITLE
Implement 80 to 443 redirection in LoadBalancer

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#380]

**Comment by GINAGC** [comment]
@rashidhussain1087, @gurunathg is this ready?

**Comment by gurunathg** [comment]
@GINAGC This will be ready for QA once https://github.com/k8-proxy/k8s-compliant-kubernetes/pull/88 is merged

**Comment by gurunathg** [comment]
https://github.com/k8-proxy/k8s-compliant-kubernetes/tree/develop/CF%20Templates
