### ISSUE TITLE
Tidy up naming conventions and endpoint support in CloudSDK - APIs

### ISSUE THREAD

**Issue by luker-GW** [k8-proxy/cs-k8s-api#406]
Under Analyse endpoints - we use Rebuild-zip-from-base64 and rebuild-zip-from-file when in actual fact we are not rebuilding anything.

<br/>

We need to bring greater precision on what actions the endpoints perform. Don't use words which only serve to confuse the user, like rebuild when not rebuilding the file.

<br/>

We should be making the Rebuild and Analyse endpoints have partity. At the moment the decision on which endpoints to support seems random. Sometimes we only have binary file support, sometimes we only have base64 support.

**Comment by mohitsengarr** [comment]
@GINAGC above mentioned endpoints are rebuilt(sanitize) the file and doing analyse both. Can suggest what should be the good name for these endpoints? what are the endpoints that should be rename?

**Comment by GINAGC** [comment]
> @GINAGC above mentioned endpoints are rebuilt(sanitize) the file and doing analyse both. Can suggest what should be the good name for these endpoints? what are the endpoints that should be rename?

Yes, we will provide more details once that it is ready for dev.

**Comment by farringtonp** [comment]
I've made some updates to the openapi.json file

**Comment by GINAGC** [comment]
@Lestat06 assigning to you to QA in develop:

- Please notice the updates on swagger from SDK to API, see PR https://github.com/k8-proxy/cs-k8s-api/pull/485/files
- All updates from https://github.com/k8-proxy/cs-k8s-api/issues/471

**Comment by Lestat06** [comment]
@GINAGC gave my review for this in #471
