### ISSUE TITLE
VM needs 10 minutes to start after deployment

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#417]
after instance says "running" the vm needs 10 minutes so that u can access filedrop or swagger and that the endpoints work. otherwise you will get GW_ERROR
Also the Release_TAG in AMI is null. which was working before
AMI: 
eu-west-1: ami-062b9cf4136d0584b
eu-west-2: ami-0247545f144eb16b4
eu-west-3: ami-0a01c90c28e7ce746
us-east-1: ami-09106a87b3a18d8b4
us-east-2: ami-0797b2ae3eae89408
us-west-1: ami-0ac455317b52670c5

workflow:  https://github.com/k8-proxy/GW-Releases/actions/runs/978546203
SDK version 0.4.0
![image](https://user-images.githubusercontent.com/6232283/123642265-62ebaf00-d823-11eb-89d7-9c65f7da0166.png)

**Comment by mohitsengarr** [comment]
@GINAGC @Lestat06 It seems rabbitMQ not up and running and api not able to make connection due to this. It is a deployment issue why rabbitmq not up and running. is it for all deployment?

**Comment by Lestat06** [comment]
@mohitsengarr yes. last night tried new ami and still had the same issue. after instance is ready to go, first minutes u cant access filedrop or swagger, after few minutes u can access filedrop and swager but they dont work

**Comment by mohitsengarr** [comment]
@Lestat06 Can you share the ip please?

**Comment by Lestat06** [comment]
shared on dm

**Comment by Lestat06** [comment]
This issue is replicated also when you boot the VM.
FYI @GINAGC

**Comment by Lestat06** [comment]
this seems to be fixed in the latest from develop. i shut down the machine and booted it up again. opened the IP as soon as the vm passed the 2 health checks and all was good and was able to rebuild
![image](https://user-images.githubusercontent.com/6232283/126794856-5f5647f9-c454-463c-aa6a-efff663e361b.png)

![image](https://user-images.githubusercontent.com/6232283/126795092-0a58140d-7bc1-4ff6-a355-796402075a15.png)
