### ISSUE TITLE
207 response for /zipfile and /protectedzipfile

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/cs-k8s-api#431]
@mohitsengarr 
We are getting response 207 for endpoints 

/api/rebuild/zipfile
/api/rebuild/protectedzipfile

This is reported from BDD test here

https://github.com/k8-proxy/GW-Releases/runs/2949518398?check_suite_focus=true

This was unnoticed in previous QA testing as we are getting a zip response back but with 207 response

To replicate this issue. Please use below URL and file

http://gw-cloud-sdk-455649808.eu-west-1.elb.amazonaws.com/swagger/index.html

[test.zip](https://github.com/k8-proxy/cs-k8s-api/files/6739120/test.zip)

**Comment by GINAGC** [comment]
@samarthdd so it looks that we need to update the documentation to mention that folders are not supported. @mohitsengarr folders are not supported at all?

**Comment by Lestat06** [comment]
@GINAGC endpoint accepts and rebuilds zips with folders inside and rebuildds the file inside folder.
below zip can be used to replicate
[pdf-with-folder.zip](https://github.com/k8-proxy/cs-k8s-api/files/6769678/pdf-with-folder.zip)

**Comment by samarthdd** [comment]
this is replicated and fixed
