### ISSUE TITLE
x-adaption-file-id with large files

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#449]
testing on f2f with large files, when failing triggers x-adaption-file-id error

**Comment by GINAGC** [comment]
@ggrig can you review this one as next priority?

**Comment by Lestat06** [comment]
when u run the file alone it gets processed but in f2f with other files sometimes fails.
It is mostly when pod accepts file and due to traffic or resource , it fails and response wont be proper

**Comment by dpatel7** [comment]
@Lestat06 can you share log to confirm response code from server?

**Comment by ggrig** [comment]
@Lestat06 
Please share file samples that cause the issue

**Comment by Lestat06** [comment]
will share in channel since are large file and some not supported

**Comment by ggrig** [comment]
@Lestat06 
I do not reproduce the issue with the recent version of CS SDK when sending the files with PostMan 
I get x-adaptation-file-id for both files:

![image](https://user-images.githubusercontent.com/26714598/124730902-cf049c00-df22-11eb-8270-89fc7a8081a8.png)

![image](https://user-images.githubusercontent.com/26714598/124730979-df1c7b80-df22-11eb-8a83-dfe3a5489673.png)

**Comment by Lestat06** [comment]
@ggrig add the large files in a scenario with other files and run that scenario with the IP.
or if u have the jp-test scenario that can do also.

**Comment by ggrig** [comment]
@Lestat06 
This is about CDR F2F plugin scenarios. Right?
I believe what happens there is that when the API server gets overload it does not respond because of TCP connection timeout.
So no HTTP response is sent. I will investigate that on F2F side

**Comment by ggrig** [comment]
Here is the PR that fixes this one

https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/594

**Comment by GINAGC** [comment]
@Lestat06 this needs to be tested once that we have a new F2F release v0.15.0, lets keep an eye on https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/594

**Comment by Lestat06** [comment]
@GINAGC will create a duplicate of my cdr and pull the latest from develop and check this once i fund some time.

**Comment by Lestat06** [comment]
this is fixed and now errors are more user frinedly in the latest commint in develop branch. thank you @ggrig 
the below img is from ck8s-classic which had this issue with most of the files.
![image](https://user-images.githubusercontent.com/6232283/125360633-7131e300-e36c-11eb-9868-cd51e4db7c9d.png)
