### ISSUE TITLE
Static code analysis vulnerability

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#450]
Fix [this](https://github.com/k8-proxy/cs-k8s-api/security/code-scanning), please.

**Comment by GINAGC** [comment]
@mohitsengarr please review this vulnerability.

**Comment by GINAGC** [comment]
@Lestat06 for QA regression.

**Comment by Lestat06** [comment]
@mohitsengarr can i have more info please/

**Comment by mohitsengarr** [comment]
@Lestat06 there is nothing to test for you in this ticket. Actually, there was a unused file which had some code scanning vulnerability. and this file has deleted in this fixed. @GINAGC

**Comment by Lestat06** [comment]
Ok i will just try the endpoints for regression then. Thanks
