### ISSUE TITLE
Specific file - endpoints dont give GW_FAILED with file with issue

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#453]
`/api/rebuild/file` returns `This endpoint doesn't accept the zip file.`
`/api/SDK/rebuild-zip-from-base64`  returns  `Report xml not exist for file 1663e694-df8e-4b9e-831f-f43eefcbaba0`
[Office2016_Issue0501002F.docx](https://github.com/k8-proxy/cs-k8s-api/files/6759127/Office2016_Issue0501002F.docx)
this happens with all endpoints

**Comment by mohitsengarr** [comment]
@Lestat06 is this still an issue?

**Comment by Lestat06** [comment]
@mohitsengarr  @GINAGC 

`/api/rebuild/file`  and   `/api/SDK/rebuild-zip-from-base64` now give the below pic as response which is ok since is a file with issues

![image](https://user-images.githubusercontent.com/6232283/127893094-dc7eca03-d6ac-4efe-b785-3e26944b68fe.png)
