### ISSUE TITLE
Endpoints return the file with different name

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#454]
`/api/rebuild/file`  returns the rebuild file with different name. (the file ID name)
`/api/rebuild/zipfile` returns a zip file with different name (the file ID name) however the files inside have their original name
same goes for `/api/rebuild/protectedzipfile`

u can replicate by using any file in the endpoints with the respected file type

**Comment by mohitsengarr** [comment]
@Lestat06 is it an issue? Could you please explain this what i need to fix? Also, please check this https://github.com/k8-proxy/cs-k8s-api/issues/429 too.

@GINAGC

**Comment by Lestat06** [comment]
@mohitsengarr basically when u rebuild a file e.g `test1.pdf` u get in return the rebuild file with name `31dbbd35-c4e2-49d1-8053-a14f133efbf4.pdf`
is the change for penetration in issue #429 related to this?

**Comment by mohitsengarr** [comment]
> @mohitsengarr basically when u rebuild a file e.g `test1.pdf` u get in return the rebuild file with name `31dbbd35-c4e2-49d1-8053-a14f133efbf4.pdf`
> is the change for penetration in issue #429 related to this?

Yes @Lestat06

**Comment by Lestat06** [comment]
@GINAGC how dou want to proceed with this. in case of filedrop and the endpoint that f2f is using this is not the case. we get the file with its original name. so basically this will happen if u use the endpoints: `/api/rebuild/file`, `/api/rebuild/zipfile`, `/api/rebuild/protectedzipfile`  from swagger or postman

**Comment by GINAGC** [comment]
@Lestat06 just document this for now on wiki.
