### ISSUE TITLE
cs-api is taking longer time to process the files - classic version

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#467]
The api has become slower in comparison with 2 weeks before in version 0.6.0.

You can notice this with running the scenario-1000 files in f2f
previous time was: 30-32 minutes (v0.4.0)
current time is : 50-60 minutes (v0.6.0)
this can be also noticed with zip files with amount of 15+ files inside.
it takes too much time and throws timeout:600 error. 
Have tested even with 0.4.0 to see of its a regression but happen the same.
this needs investigation also from icap-service side. might be related to issue #455 

![1k-25th-0 6 0](https://user-images.githubusercontent.com/6232283/124896717-f9675f80-dfdd-11eb-9265-e6a287989ac0.png)

**Comment by ggrig** [comment]
Most probably this relates to ICAP Adaptation failures introduced with recent builds
@Lestat06 - did you try to verify if adaptation failures are there during the processing:

![image](https://user-images.githubusercontent.com/26714598/125048459-ff7a4080-e0b0-11eb-8d3d-69c6dd427c9d.png)

Also please specify icap adaptation AMIs/OVAs that work and that fail

**Comment by Lestat06** [comment]
@ggrig this is the status of the rebuild pods while running slowly the classic version in ck8s
![image](https://user-images.githubusercontent.com/6232283/125358409-2367ab80-e369-11eb-9411-006ccd9478b6.png)

**Comment by Lestat06** [comment]
@ggrig 
![image](https://user-images.githubusercontent.com/6232283/125365881-5c0d8200-e375-11eb-8012-380bb099baaa.png)

and this one is from classic k3s sdk. after 4 files left there were no rebuild pod is being created
the below pic with no rebuild pods is when the idle part is in the end of the process. u can check in the above pic in the end at 00.50 it topped creating rebuild pods
![image](https://user-images.githubusercontent.com/6232283/125365615-dee20d00-e374-11eb-86df-ffbc51d14f3b.png)

this one os after it started proccessing the last files
![image](https://user-images.githubusercontent.com/6232283/125365812-3b452c80-e375-11eb-8611-5ba81dbac2ed.png)

**Comment by mohitsengarr** [comment]
@Lestat06 please test on latest and let me know about this issue.

**Comment by Lestat06** [comment]
@mohitsengarr cant test this uet since engine version is missing and cant connect to the f2f

**Comment by GINAGC** [comment]
Closing, not fixing for now.
