### ISSUE TITLE
CI/CD updates for GW Cloud SDK

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#47]
Add pipeline for GW Cloud SDK with centos.
Document very detailed the workflow for GW cloud SDK centos and ubuntu.
Fix the CD with AMI.

**Comment by gurunathg** [comment]
Fixed CD with AMI - https://github.com/k8-proxy/GW-Releases/runs/2298234618?check_suite_focus=true 
Working on centOS version

**Comment by gurunathg** [comment]
Updated documentation and created a PR: https://github.com/k8-proxy/GW-Releases/pull/253

**Comment by GINAGC** [comment]
will merge this with the rest of the CI/CD for next week
