### ISSUE TITLE
Analyse required updates on swagger

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#471]
@ggrig see epic https://github.com/k8-proxy/cs-k8s-api/issues/406, we need to anaylse the updates needed in swagger. Here are some comments:

- We need to match the Rebuild versus the Analyse endpoints to have parity
- We need to have parity between the binary and the base 64. 
- We need to remove "rebuild" from the analyze endpoints.
- We need to update the ones under SDK to make more clear the goal of those. 
- I think we can move the GET from xmlreport to the detail section.

Can you do some analyse and suggest the list of updates needed?

Other updates:
- Update title from Glasswall File Rebuild Product API to Glasswall Cloud SDK API
- Update description 
- Review wording in all descriptions for all endpoints

**Comment by GINAGC** [comment]
@Lestat06 please test this one on develop and send me a link to swagger with these changes, I need to review with the product team if they would like any additional updates.

**Comment by Lestat06** [comment]
@GINAGC i checked these from the golang version from develop branch. the following are the observations
- title is not "Glasswall Cloud SDK API" but Glasswall Cloud API
- in the ANALYSE section this phrase doesnt make sense for me _"On success, the Report file returned in the response body."_
needs to be changed to "On success, the Report XML file is returned in the response body". Also in _"Analyse a binary file for presence of malicious data."_ ANALYSE-->ANALYSES which give the meaning that the endpoint analyses.
- `/api/rebuild/file` has the same issue _"On success, the Rebuilt file returned in the response body."_ needs to be "On success, the Rebuilt file is returned in the response body."
- these 2 endpoints `/api/composite/rebuild-zip-from-file` and `
​/api​/composite​/rebuild-zip-from-base64` in the description where it says what the zip archive has inside, we have to include also the metadata.json not only the rebuild file and the xml file.
- in the description here `/api/filetypedetection/base64`  _"On success, the file type returned in the response body."_ needs to be changed to "On success, the file type is returned in the response body."
- `/api/detail/version` this one in the description need to be added that it says also the type of the platform. and later on as we will be adding also if its prod or eval.
- `/api/analyse/xmlreport` needs in description to be added that returns report xml of a file previously rebuild by using its x-adaption-file-id
- Also all the file endpoints that get base64 from file dont have the place where u upload the file to get its base64 encoded representation, which makes them unusefull.

**Comment by GINAGC** [comment]
@Lestat06 

1.- Is expected
2 and 3.- Agree, please do the updates and send a PR.
4.- please also send a PR with the update.
5.- please send PR
6.- please send PR
7.- agree, please send PR.
8.- please open an issue
9.- please open a P1 issue and send on channel for Mohit to comment.

Thank you!

**Comment by Lestat06** [comment]
@GINAGC will confirm the above also in the new trigger  for the classic from the above and then take action
