### ISSUE TITLE
Typos in the meaning of some phrases in Swagger

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#494]
1.- in the ANALYSE section this phrase doesn't make sense for me "On success, the Report file returned in the response body."
needs to be changed to "**On success, the Report XML file is returned in the response body**". 

2.- In "Analyse a binary file for the presence of malicious data." ANALYSE-->ANALYSES which give the meaning that the endpoint analyses.

3.- /api/rebuild/file has the same issue "On success, the Rebuilt file returned in the response body." needs to be **"On success, the Rebuilt file is returned in the response body."**

4.- these 2 endpoints /api/composite/rebuild-zip-from-file and ​/api​/composite​/rebuild-zip-from-base64 in the description where it says what the zip archive has inside, we have to include also the metadata.json not only the rebuilt file and the xml file.

5.- in the description here /api/filetypedetection/base64 "On success, the file type returned in the response body." needs to be changed to **"On success, the file type is returned in the response body."**

6.- /api/detail/version this one in the description need to be added that it says also the type of the platform. and later on as we will be adding also if it's prod or eval.

7.- /api/analyse/xmlreport needs in description to be added that returns report xml of a file previously rebuild by using its x-adaption-file-id

**Comment by Lestat06** [comment]
1- is ok just missed a dot in the end of the sentence but it makes sense now
![image](https://user-images.githubusercontent.com/6232283/126774304-5b37aa71-3a68-41e2-b6a2-e33a417fecbe.png)
2- needs to be in both analyse endpoints 
![image](https://user-images.githubusercontent.com/6232283/126777704-6b99849e-0d0d-4f9e-8a4b-96f74f8e74b9.png)
3-  is ok
4- is ok
5- is ok
6- has no changes 
![image](https://user-images.githubusercontent.com/6232283/126778458-7e8f589f-40cf-4d24-8dd4-d08a9bd064b2.png)

7- is ok
![image](https://user-images.githubusercontent.com/6232283/126778157-20f53efb-f5b8-4fec-96db-17e12aa9520b.png)

FYI @GINAGC @mohitsengarr

**Comment by mohitsengarr** [comment]
@Lestat06 for 6th point, I have added with "additional information". In description can't specify every property. user can check the example value and schema, below. For other point will check-in.

![image](https://user-images.githubusercontent.com/43764140/126779784-5b914cf7-76ea-44a8-9052-97cfb4f6b980.png)

**Comment by Lestat06** [comment]
@GINAGC this is ok now and confirmed
