### ISSUE TITLE
Rename SDK/Composite section endpoints

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#496]
Rename endpoints on swagger and on code:

1.- From /api/sdk/rebuild-zip-from-file to /api/composite/rebuild-zip-from-file

2.- From /api/sdk/rebuild-zip-from-base64 to /api/composite/rebuild-zip-from-base64

Note: I will hold this in develop to merge it alone to main and sync releases with F2F.

**Comment by Lestat06** [comment]
this is ok in develop and confirmed 
![image](https://user-images.githubusercontent.com/6232283/126773655-c69a5455-33d4-4750-afc6-3134df955b5d.png)
