### ISSUE TITLE
Missing SDKEngineVersion for classic

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#504]
BDD test cases are failing due to missing SDKEngineVersion header for classic.

**Comment by Lestat06** [comment]
@mohitsengarr  this is still an issue. also BDD test failed
![image](https://user-images.githubusercontent.com/6232283/126551444-52f6e212-29a2-430b-bb74-d7da752b668d.png)
![image](https://user-images.githubusercontent.com/6232283/126551478-78b8ab9a-d4ea-4151-a616-c5b505beb349.png)

**Comment by mohitsengarr** [comment]
@Lestat06 now, it is confirmed that environment variable isn't set.

**Comment by Lestat06** [comment]
@GINAGC FYI

**Comment by GINAGC** [comment]
Not fixing for now, since we are depecrating classic.
