### ISSUE TITLE
Remove local type check for api/rebuild/zipfile

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#530]

**Comment by Lestat06** [comment]
@GINAGC the endpoint seems to be ok
tested with zip with:
excel
pdf
powerpoint
word
mix
with 19 files inside pdf
with 26 files inside pdf
with 29 files inside pdf
however at 30 files inside it fails. pods dont even start. it seems that is the limit

**Comment by GINAGC** [comment]
@Lestat06 please open separate issues for the 30 files inside issue. We need to review for next release.

**Comment by Lestat06** [comment]
Updated comment above
