### ISSUE TITLE
Enforce secure deployment to Cloud SDK clients

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/cs-k8s-api#544]
While inspecting the deployments guidelines, the client is not forced to deploy the services, including infra as code securely.

**Recommended Mitigation**
The deployment is related to the customer; the customer can decide how they want to deploy the application; the security team will make a disclaimer on the deployment when the customer types the commands in the terminal, where the customer should agree on his unsecured deployment errors to prevent any liability on GW side.
This can be in a form of a T&C statement (command line??) that the customer ticks/agrees on safe deployment during installation.

**Comment by GINAGC** [comment]
@gurunathg please take a look to this one.

**Comment by gurunathg** [comment]
@PEpetra @GINAGC  Regarding https://github.com/k8-proxy/cs-k8s-api/issues/544, 
Currently, to deploy ck8 based cloudSDK, our recommended method is to use cloudformation template which has been hardened based on our security practices. In cases where the stack is deployed directly using AMI, we will have certain ports exposed (Ref https://github.com/k8-proxy/go-k8s-infra/issues/94). 
1. We can disable deployment of services which create listeners to open world (e.g., K8 dashboard, ICAP 1344 service) during the deployment phase. 
2. Disabled password based SSH login and installed fail2ban to prevent SSH brute force attacks ( Already implemented in EAP-Releases repo)
3. Use security hardened base image (which is being evaluated to verify compatibility with cloudSDK) 

Question: #1, #3 -  Do we need to implement these changes in existing repos or can we consider them in new solution?

**Comment by gurunathg** [comment]
Summary of discussion with Infosec team: Can be considered closed as we are enforcing security guidelines at CF and terraform level

**Comment by GINAGC** [comment]
based on the discussion, this is now closed.
