### ISSUE TITLE
Composite endpoints fail to process zip files

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#553]
`api/composite/rebuild-zip-from-file`  and  `api/composite/rebuild-zip-from-base64` fail to process the zip file while there is no restriction for zip files.
Error:  Report XML not exist for file 
Replicate by trying to rebuild a zip file in the endpoints above

![image](https://user-images.githubusercontent.com/6232283/127475928-5aaf8f53-f1bb-44a7-abd0-cd817f740729.png)

**Comment by Lestat06** [comment]
this is working in develop, however the xml format does not have the usual format

**Comment by GINAGC** [comment]
for @Lestat06 to test and close.

**Comment by Lestat06** [comment]
this is a feature now in the latest version. closing FYI @GINAGC
