### ISSUE TITLE
Deprecate Cloud API classic

### ISSUE THREAD

**Issue by luker-GW** [k8-proxy/cs-k8s-api#558]
Template EAP EPIC

**Comment by GINAGC** [comment]
@gurunathg please deprecate classic version on eap-releases.

**Comment by gurunathg** [comment]
@GINAGC Classic is removed from EAP-Releases

**Comment by Lestat06** [comment]
@GINAGC this is not an option anymore in eap-releases to trigger
FYI @SwathiYerabolu
