### ISSUE TITLE
GW K8s Compliant API returns HTTP status as 400 in all the failure cases

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/cs-k8s-api#58]
[NEW QUOTATION  AGREEMENT.doc.zip](https://github.com/k8-proxy/cs-k8s-api/files/6297157/NEW.QUOTATION.AGREEMENT.doc.zip)
[sample4-tagged.xlsx](https://github.com/k8-proxy/cs-k8s-api/files/6297158/sample4-tagged.xlsx)

Currently we do not have any way from the gw cloud sdk response to determine if the file was
1. Unsupported
2. Malicious
3. Corrupt
In all cases for now we get 400 and we return that the file was infected and block download from Menlo.
Can we please get a deterministic result from gw-sdk, so we can mark unsupported files as allow for download and malicious ones as blocked.
This will be very important to have to complete handling of malicious files.

**Scenarios:**
1. **File with Virus**

NEW QUOTATION  AGREEMENT.doc
{
    "errors": [
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <title>Policy Issue</title>\n</head>\n<body>\n    <h1>Document Access Blocked due to Policy</h1>\n    The file does not comply with the current policy\n    <br>\n    The file id blocked is:\n    <strong>89bb65bd-8381-4e2d-8a7a-d4b771546988</strong>\n    <br />\n    <p>\n        For more information contact your system administrator\n        <hr>\n    </p>\n</body>\n</html>"
    ],
    "status": "GW_FAILED"
}

2. **Unsupported File (test file used by Menlo, a simple text file)**
test_file
{
    "errors": [
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <title>Policy Issue</title>\n</head>\n<body>\n    <h1>Document Access Blocked due to Policy</h1>\n    The file does not comply with the current policy\n    <br>\n    The file id blocked is:\n    <strong>d52b10a3-dcd2-4992-b053-3d2ef51a52b8</strong>\n    <br />\n    <p>\n        For more information contact your system administrator\n        <hr>\n    </p>\n</body>\n</html>"
    ],
    "status": "GW_FAILED"
}

3. **Polyglot File which GW was not able to process**

sample4-tagged.xlsx
{
    "errors": [
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <title>Policy Issue</title>\n</head>\n<body>\n    <h1>Document Access Blocked due to Policy</h1>\n    The file does not comply with the current policy\n    <br>\n    The file id blocked is:\n    <strong>1d9eae66-9e39-4d85-834b-7ef34289df52</strong>\n    <br />\n    <p>\n        For more information contact your system administrator\n        <hr>\n    </p>\n</body>\n</html>"
    ],
    "status": "GW_FAILED"
}

**Comment by GINAGC** [comment]
@mohitsengarr please document the latest updates on readme and swagger.

**Comment by mohitsengarr** [comment]
> @mohitsengarr please document the latest updates on readme and swagger.

@GINAGC  here is the [pull](https://github.com/k8-proxy/cs-k8s-api/pull/63)

**Comment by GINAGC** [comment]
@svf97 this is fixed, please validate after Pranay deploys a new instance.
