### ISSUE TITLE
Update for the minio based icap-adaptation

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#59]
the minio based icap-adaptation(#k8-icap-go-adaptation-service) which is much faster than current implementation, the files are not stored in local file systems (i.e. original store, rebuild store PVCs) but instead it uses minio to store and retrieve the files. So we need to make few changes in the cs-k8s-api code to make it work.

**Comment by mohitsengarr** [comment]
I, @pranaysahith and @azopat had a call yesterday and as per the @azopat there is no modification is required in the code. Currently @azopat is testing the api and will share the details.

@GINAGC

**Comment by GINAGC** [comment]
ok, please confirm once you tested @azopat
