### ISSUE TITLE
Version number of the SDK engine (not hardcoded) 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#65]
@mohitsengarr  add an enpoint for this and also add to the header.

- Option 1: we may beed the hash of the repo from the docker version we are using. 
- Option 2: call the container from code. / Check the logs, it may be there. / Capture the events from a transaction ID.

@gurunathg and @pranaysahith to also review and comment the best way to do this. 

Let me know if we need to contact the internal team to get more info.

**Comment by mohitsengarr** [comment]
@GINAGC I think it is completed with auto tagging.
