### ISSUE TITLE
gw cloud sdk ova requires ./flush_iptables manual step

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/cs-k8s-api#91]
Sometimes GW Cloud sdk OVA requires 
./flush_iptables.sh 
k3s restart.

Run it on server boot

**Comment by GINAGC** [comment]
@Lestat06, @svf97  is this still an issue?

**Comment by svf97** [comment]
@GINAGC i haven't seen it in recent releases.

**Comment by Lestat06** [comment]
I haven't seen this either in the latest tests we did

**Comment by GINAGC** [comment]
then I am closing.
